### ISSUE TITLE
[BUG] less解析成css，有多余的css代码

### ISSUE THREAD

**Issue by xiaoxiaodemeng** [alibaba/rax#2328]
### ⌨️

- [ ] Would you like to work on a fix?

### Where is the bug from?

Rax App

### Minimal code and steps to reproduce the bug

// index.module.less
```less
:root {
  --button-background: #333;
}

.homeContainer {
  align-items: center;
  margin-top: 200rpx;
  background-color: var(--button-background);
}
```
// 最后编译
```css
.Home--homeContainer--68rPAEN {
  align-items: center;
  margin-top: 26.66667vw;
  background-color: #444;
  background-color: var(--button-background);
}
```
` background-color` 多了一次赘余的

### Current and expected behavior

// 预期取var的全局变量，`background-color: #444;`这一次可以跳过
```css
.Home--homeContainer--68rPAEN {
  align-items: center;
  margin-top: 26.66667vw;
  background-color: var(--button-background);
}
```

### Environment

"rax": "^1.1.0"
"rax-app": "^3.8.7"

### build.json

```json
{
  "targets": [
    "web"
  ],
  "webpack5": true,
  "web": {
    "mpa": true,
    "pha": true
  },
  "plugins": [
    "@ali/build-plugin-rax-app-def",
    [
      "@ali/build-plugin-event-tracking-register",
      {
        "goldlog": false
      }
    ]
  ]
}

```
